branchInfo:
  feature/FT1:
    ispwBranch:       QA1
    mapRule:          per-branch
    loadLib:          SALESSUP.<ispwApplication>.QA1.LOAD
  feature/FT2:
    ispwBranch:       QA2
    mapRule:          per-branch
    loadLib:          SALESSUP.<ispwApplication>.QA2.LOAD
  feature/FT3:
    ispwBranch:       QA3
    mapRule:          per-branch
    loadLib:          SALESSUP.<ispwApplication>.QA3.LOAD
  bug:
    ispwBranch:       EMR
    mapRule:          per-branch
    loadLib:          SALESSUP.<ispwApplication>.STG.LOAD
  master:
    ispwBranch:       STG
    mapRule:          per-branch
    loadLib:          SALESSUP.<ispwApplication>.STG.LOAD
cesUrl:               http://cwcc.compuware.com:2020
tttVtEnvironmentId:   192.168.96.130:16196
tttNvtEnvironmentId:  5cee98c2d3142c1f90a4976d
tttConfigFolder:      'git2ispw/TttConfigurations'
tttRootFolder:        'MainframeTests'
tttVtFolder:          'Unit Tests'
tttNvtFolder:         'Module Integration Tests'
ccSources:            'MainframeSources'
ccDdioOverrides:
  - SALESSUP.<ispwApplication>.FIX.LOAD,
  - SALESSUP.<ispwApplication>.EMR.LOAD,
  - SALESSUP.<ispwApplication>.DEV1.LOAD,
  - SALESSUP.<ispwApplication>.DEV2.LOAD,
  - SALESSUP.<ispwApplication>.DEV3.LOAD,
  - SALESSUP.<ispwApplication>.QA1.LOAD,
  - SALESSUP.<ispwApplication>.QA2.LOAD,
  - SALESSUP.<ispwApplication>.QA3.LOAD,
  - SALESSUP.<ispwApplication>.STG.LOAD,
  - SALESSUP.<ispwApplication>.PRD.LOAD
sonarScanner:       scanner
sonarServer:        CWCC